### ISSUE TITLE
would you please  support  EmbeddingLayer  and  Lstm   Gru RNN Layer   and  Attention  Transformer Layer 

### ISSUE THREAD

**Issue by mullerhai** [pashashiz/scanet3#89]
HI  :   
        Great Project !  If  we  could   support  EmbeddingLayer  and  Lstm   Gru RNN Layer   and  Attention  Transformer Layer  ,this  project  will have bigger  impect for  scala  deep learning. In  my project ,I always need some  rnn  lstm layer  to deal with  text  & nlp . Please  If we have idea and time ,develop some rnn layer , I think  I will use this
      thank

**Comment by pashashiz** [comment]
Hi, the project was on hold for a while. I think I can add those soon.

**Comment by pashashiz** [comment]
Hi, @mullerhai. Just added LSTM layer.
